steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/uma-tech-ai-lab/smartaudit-api:latest', '.']

  # Push the container image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/uma-tech-ai-lab/smartaudit-api:latest']

images:
  - 'gcr.io/uma-tech-ai-lab/smartaudit-api:latest'

options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: projects/uma-tech-ai-lab/serviceAccounts/117511395113-compute@developer.gserviceaccount.com
