steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/uma-tech-ai-lab/rag-agent-backend', '.']
images:
  - 'gcr.io/uma-tech-ai-lab/rag-agent-backend'
options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: 'projects/uma-tech-ai-lab/serviceAccounts/117511395113-compute@developer.gserviceaccount.com'
